[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
bitcoin = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
plonky2 = "1.1.0"
rand = "0.8"
lazy_static = "1.5.0"
hex = "0.4.3"
bip39 = "2"

[dependencies.getrandom]
version = "0.2.15"
features = ["js"]
